services:
  evolution_api:
    image: atendai/evolution-api:latest
    platform: linux/amd64          # ✅ Corrigido (era "plataform")
    container_name: evolution_api
    depends_on:
      - evolution-db
      - redis
    env_file:
      - .env 
    ports:
      - "8080:8080"
    networks:
      - evolution-net
    
  evolution-db:
    image: postgres:15
    container_name: evolution-db
    environment:
      - POSTGRES_USER=evo
      - POSTGRES_PASSWORD=senha_magica
      - POSTGRES_DB=evolution   
    volumes: 
      - evolution_postgres_data:/var/lib/postgresql/data
    networks:
      - evolution-net
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - evolution-net

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - evolution-net
  volumes:
  evolution_postgres_data:
  redis-data:
  n8n_data:

networks:
  evolution-net:
